import { useRouter } from "next/router";
import Head from "next/head";
import SearchResults from "@/components/_pages/Search/SearchResults";
import Loading from "@/components/_shared/Loading";
import Layout from "@/components/_shared/Layout";

export default function Search() {
    const { query } = useRouter();

	return (
		<>
			<Head>
				<title>Pexels App - Search</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout className="py-[150px]">
				{Object.keys(query).length !== 0 ? 
                	<SearchResults/>
					:
					<Loading/>
				}
			</Layout>
		</>
	);
}